version: '3.8'

services:
  sql_server_utn:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_utn
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Utn_password2026!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:

